### ISSUE TITLE
Build File Extractor

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data_tools#24]
Need a script to find and extract images in TIF format (identified in a CSV file) from a folder system organized by year and month. Some details:

- the CSV contains two pertinent fields: ACCNB (identifier) and ACCDATE (needed to navigate to the appropriate folder)
- only the folder pertaining to the ACCDATE should be looked at; if the image does not exist in that folder, it should be identified as missing

Two outputs:

1) a folder with the files copied from the original file structure (don't delete the original files)
2) a new CSV which has an additional column, detailing whether the file was "Found" or "Missing"

I've created a fake folder with fake files and a fake list to test (will email over shortly)

**Comment by jovenc** [comment]
To clarify, is the input going to be just ACCNB (identifier)? And then I would have to use the lookup file to get ACCDATE, then navigate to the related folder and produced the two outputs stated above?

**Comment by aharpalaniTO** [comment]
yup so if ACCNB is 123456, and the ACCDATE is 2018-05-04,

you would try to pull [path]/2018/05/123456.tif

If it exists, set the new column to "Found" and copy the image over
If it doesn't, set the new column to "Missing"



(the actual images have a 2-digit year prefix, but don't worry about this for now)

**Comment by jovenc** [comment]
The script can currently be run with the command line `python3 pull_collision_images.py get-date --identifier=12421234` where the identifier is whatever we want it to be. Note that it can only take in a single string at a time.

The identifier will be considered to be 'Missing' in the output csv file when the identifier is not found in the lookup table or when there isn't any matching file/images found in the folder.

Note that the output folder is in 'a' (append) instead of 'w' (write) mode as that simplifies the script when trying to include identifiers that aren't found.

Let me know if there are more changes that have to be done!

**Comment by jovenc** [comment]
Once everything is done and confirmed, we only have to change a few things in the script.

1. source_file (csv file) `L21`
2. target_file (csv file) `L22`
3. file_path (where the images are stored) `L49`
4. dest (where we want to copy those images to) `L50`
5. date format accordingly `L35`

**Comment by jovenc** [comment]
A few things to take note of:
- when `ACCNB` = `1.99001E+11`, we would have to change the format to number (general and text wouldn't work) in Excel
- but then when we convert that, we will also convert `081019847` to `81019847` (even though I have only selected a few cells to format) which would not result in any images found
- Always use Notepad to read the file instead of Excel to have a better picture on what the csv file is like to the script.

However, such problem do not exist in the actual file, so I guess there's nothing to worry about? LOL
But I just want to keep this here for future reference ( •̀ ω •́ )y

**Comment by jovenc** [comment]
Pulling collision images is complete! The whole process took about an hour.

Out of 2900 rows/identifier (2270 in P01, 630 in P02):
- 2828 found (2245 in P01, 583 in P02)
- 72 missing (25 in P01, 47 in P02)

Results are in the folder K:\tra\GM Office\Big Data Group\Work\Collision Image Puller\destination

**Comment by jovenc** [comment]
Will record down the latest steps to pull images.

1) Create a couple of folders. 
- a folder named `destination` (acts as a main folder that contains folder of images)
- folders named `P04` / `P05` / `P06` / `whatever_the_project_id_is`  etc (these are the folders where images belonging to each project will be put into)
- a csv file named `results.csv` with only 4 columns which are `PROJECT_ID` , `ACCNB` , `ACCDATE` , `STATUS`

2) Fix the file path and date format in the [script](https://github.com/CityofToronto/bdit_data_tools/blob/new_file_extractor/file_extractor/pull_collision_images.py).
- L23: source_file (csv file)
- L24: target_file (csv file)
- L52: file_path (where the images are stored)
- L54: dest (where we want to copy those images to)
- L46: date format

3) Run script with the command line  
`python pull_collision_images.py get-date`

**Comment by jovenc** [comment]
Pulling collision images is complete! The whole process took more than 12 hours given that the file size this time is 10 times bigger than before. Out of 30671 rows/identifier, I found xxx of them and xxx of them are not found. The summary is in the table below.

|project|rows|found|missing|
|--|--|--|--|
|P04|5792|5677|25|
|P05|181|179|2|
|P06|169|168|1|
|P07|3839|3832|6| 
|P08|11182|11137|45|
|P09|2384|2377|7|
|P10|282|280|2|
|P11|4597|4573|24|
|P12|2335|2328|7|
|TOTAL|30671|30551|119|

**Note:** One row is missing in the results file for project P07 because that row has a bigger than usual ACCNB and a future date for ACCDATE as shown below.

|PROJECT|ACCNB|ACCDATE|
|--|--|--|
P07 | 23188069124 | 12/18/2023

Results are now in the folder K:\tra\GM Office\Big Data Group\Work\Collision Image Puller\ **part_2** \destination
