### ISSUE TITLE
Multiple options for downloaded file format (i.e. shp, csv, geojson)

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data_tools#7]
Possible avenue: https://gis.stackexchange.com/questions/77109/json-to-shapefile-in-javascript

**Comment by chelsrosic** [comment]
I think this is how I need to integrate calling a JS function on the click of a HTML link: https://community.plot.ly/t/assining-js-function-to-html-button/5271

**Comment by chelsrosic** [comment]
At first I had an issue where the provided tutorial code would not work (ie. step 2 of the [Get started](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/README.md) section) . I would run the code with gunicorn, navigate to the correct page and would see the error `Error loading layout`. I fixed it by adding this line of code into my `usage.py` file: `app.config.requests_pathname_prefix = ''`

[Source](https://community.plot.ly/t/dash-error-loading-layout/8139/6) 

P.S. this was an issue that I encountered before and I think it might be a good idea to add it to the Dash wiki.

**Comment by chelsrosic** [comment]
Wait .... https://github.com/GeospatialPython/pyshp  .... can I just use this library with my normal Dash code ????

**Comment by chelsrosic** [comment]
Trying to layout how to component will work: 

- Dash HTML component source code using react.js for [Link](https://github.com/plotly/dash-html-components/blob/master/src/components/Link.react.js) and [A](https://github.com/plotly/dash-html-components/blob/master/src/components/A.react.js) components
- Take an input CSV in the form of a string, and an optional line separator parameter in case the line separator is not `/n` (I had issues with the line separator `/n` being left out of the CSV string before so I might not want to use `/n` as a line separator)
- [Convert CSV to JSON](http://techslides.com/convert-csv-to-json-in-javascript) with JavaScript
- [Convert JSON to Shp](https://gis.stackexchange.com/questions/77109/json-to-shapefile-in-javascript)

What I need to work on: 
- How to get all `.shp` files (i.e. `.dbf`, `.prj`) into zip file  
- Attach them to an href 
- Attatch href to the link

**Comment by chelsrosic** [comment]
Tried using python since Javascript components were taking too long and  was discovered 

Original workflow idea:
1. convert dataframe to geojson 
2. convert geojson to shapefile and zip the file 
3. send to a link (similarly to how the CSV was sent to a link)

I got stuck on step 1: 
Converting a pandas dataframe to geojson was very cumbersome since it required a lot of code (look at https://gis.stackexchange.com/questions/237162/geopanda-write-geodataframe-into-shapefile-or-spatialite) . 

I also kept getting the following error when I tried to convert the dataframe to : `TypeError: ('string indices must be integers', u'occurred at index 0')`. I received this error on the line where I listed the properties of the geojson that I was trying to create. 

So I decided to look using a pandas geodataframe instead of a dataframe. I used shapely.wkt.loads() to load the Postgresql WKT geometry into python as a geometry object. I discovered that my function for converting dataframes to geojson now misaculously worked while using my geodataframe instead of a dataframe. However, geodataframes have built in functions to convert themselves to geojsons and shapefiles. 

So I am going to look into one of two new workflows:

Idea 1:
1) convert geodataframe to geojson string 
2) convert geojson string to shapefile
3) send as `href` to Dash html `a` component 

Pros: 
- This workflow would be very similar to how I converted my CSV to a CSV with geometries.

Cons: 
- Might be more code and more complicated than it needs to be 

Idea 2: 
1)  convert geodataframe to shapefile 
2) send as `href` to Dash html `a` component 

Pros: 
- might be shorter (less code, more simple to read) 

(Potential) Cons: 
- Not sure how to put this into a zip file ... not sure what happens with the `.prj`, `.dbf` files that should come with a shapefile. I am not even sure if they will be outputted ? 
- The csv file became linked to a link on the website by sending the csv file info to a `@app.server.route` call/function (similar to a callback). In this case there would be no string to send through the url link and probably no reason to make a `@app.server.route` call.  So I'm now sure how to correctly update the `href` parameter so it will be equal to a link to a shapefile. 

Anyways I think Idea 2 is promising but I need to look into the logistics of it a bit more.

**Comment by chelsrosic** [comment]
Very good resource for converting GeoJSON to shp: 

https://github.com/TipsForGIS/geoJSONToShpFile

The person who created this also made a video to briefly describe the process: 
https://www.youtube.com/watch?v=YQgEcl0qTFw
